### PR TITLE
Make crucible config distro-generic

### PR DESCRIPTION
**Pull request by rafaelfolco**
Move from /etc/sysconfig/crucible to /etc/crucible.conf.

### CODE REVIEW

**Comment by atheurer** [comment]
How does this affect our internal installer?  Does the internal installer now use the public crucible-install.sh, so there are no updates to the internal installer for manipulating the config file?

**Comment by rafaelfolco** [comment]
> How does this affect our internal installer? Does the internal installer now use the public crucible-install.sh, so there are no updates to the internal installer for manipulating the config file?
This is hardcoded in multiple places. I've changed several files in this commit: https://github.com/perftool-incubator/crucible/pull/128/commits/2cee04780e3860dbc433c64afd8a77f4fbe00b53. If the internal installer shared the same vars, we could change in the external installer only.

**Comment by atheurer** [comment]
> If the internal installer shared the same vars, we could change in the external installer only.

I was thinking that the internal installer could just call the external installer with the login credentials provided, so the internal installer does not have to know any of these details about where the config file is.

Also, what happens to existing installations that still have /etc/sysconfig/crucible?  Is there a check to find this and move it to /etc/crucible.conf?

**Comment by rafaelfolco** [comment]
> I was thinking that the internal installer could just call the external installer with the login credentials provided, so the internal installer does not have to know any of these details about where the config file is.

This looks odd, but I suppose I am missing something here. The external must call the internal, not the opposite ?

> Also, what happens to existing installations that still have /etc/sysconfig/crucible? Is there a check to find this and move it to /etc/crucible.conf?

If you installed crucible config on /etc/sysconfig, your crucible on /opt/crucible will still use it. If you run a new install, the new config on /etc/crucible.conf will be used. Old installer, old config, New installer, new config. If you want to use an old installation with the new config, you could manually copy it.

**Pull request closed without merging**
